[2025-05-05T13:30:39.459+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-05T13:30:39.488+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-05-05T13:30:36.800381+00:00 [queued]>
[2025-05-05T13:30:39.501+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-05-05T13:30:36.800381+00:00 [queued]>
[2025-05-05T13:30:39.503+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-05T13:30:39.538+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_raw_data> on 2025-05-05 13:30:36.800381+00:00
[2025-05-05T13:30:39.549+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'extract_raw_data', 'manual__2025-05-05T13:30:36.800381+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/lead_data_pipeline.py', '--cfg-path', '/tmp/tmp9q9jazjh']
[2025-05-05T13:30:39.549+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-05T13:30:39.551+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask extract_raw_data
[2025-05-05T13:30:39.552+0000] {standard_task_runner.py:72} INFO - Started process 103 to run task
[2025-05-05T13:30:39.641+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-05-05T13:30:36.800381+00:00 [running]> on host 433e63c87a30
[2025-05-05T13:30:39.817+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='extract_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T13:30:36.800381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T13:30:36.800381+00:00'
[2025-05-05T13:30:39.819+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-05T13:30:39.861+0000] {lead_data_pipeline.py:148} INFO - Started batch processing for 2025-05-05.
[2025-05-05T13:30:39.862+0000] {lead_data_pipeline.py:33} INFO - Created synthetic data for RO country code.
[2025-05-05T13:30:40.441+0000] {lead_data_pipeline.py:100} INFO - Written 993 records to the CSV file.
[2025-05-05T13:30:40.736+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/lead_data_pipeline.py", line 152, in save_raw_data
    _add_id()
  File "/opt/airflow/dags/lead_data_pipeline.py", line 109, in _add_id
    con.execute("""
duckdb.duckdb.InvalidInputException: Invalid Input Error: CSV Error on Line: 230195
Original Line: 
Dorel Ababei,dorelababei,dorelababei@acasa.ro,4560919201424,1992-10-08,"Strada Dumitrescu Nr. 98 Bl. 52  Sc. 10 Ap. 946, Topoloveni, 426727",0240 470 088,fe:1e:56:15:ea:e6,46.201.17.107,RO80OSHJ0224373664863771,2025-03-11 18:21:07,19056,856,145,1666334
Expected Number of Columns: 16 Found: 15
Possible fixes:
* Enable null padding (null_padding=true) to replace missing values with NULL
* Enable ignore errors (ignore_errors=true) to skip this row

  file=/opt/***/data/raw_data.csv
  delimiter = , (Auto-Detected)
  quote = " (Auto-Detected)
  escape = " (Auto-Detected)
  new_line = \n (Auto-Detected)
  header = true (Set By User)
  skip_rows = 0 (Auto-Detected)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding=0
  sample_size=20480
  ignore_errors=false
  all_varchar=0


[2025-05-05T13:30:40.748+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_raw_data_pipeline, task_id=extract_raw_data, run_id=manual__2025-05-05T13:30:36.800381+00:00, execution_date=20250505T133036, start_date=20250505T133039, end_date=20250505T133040
[2025-05-05T13:30:40.763+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-05T13:30:40.764+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task extract_raw_data (Invalid Input Error: CSV Error on Line: 230195
Original Line: 
Dorel Ababei,dorelababei,dorelababei@acasa.ro,4560919201424,1992-10-08,"Strada Dumitrescu Nr. 98 Bl. 52  Sc. 10 Ap. 946, Topoloveni, 426727",0240 470 088,fe:1e:56:15:ea:e6,46.201.17.107,RO80OSHJ0224373664863771,2025-03-11 18:21:07,19056,856,145,1666334
Expected Number of Columns: 16 Found: 15
Possible fixes:
* Enable null padding (null_padding=true) to replace missing values with NULL
* Enable ignore errors (ignore_errors=true) to skip this row

  file=/opt/***/data/raw_data.csv
  delimiter = , (Auto-Detected)
  quote = " (Auto-Detected)
  escape = " (Auto-Detected)
  new_line = \n (Auto-Detected)
  header = true (Set By User)
  skip_rows = 0 (Auto-Detected)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding=0
  sample_size=20480
  ignore_errors=false
  all_varchar=0

; 103)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/lead_data_pipeline.py", line 152, in save_raw_data
    _add_id()
  File "/opt/airflow/dags/lead_data_pipeline.py", line 109, in _add_id
    con.execute("""
duckdb.duckdb.InvalidInputException: Invalid Input Error: CSV Error on Line: 230195
Original Line: 
Dorel Ababei,dorelababei,dorelababei@acasa.ro,4560919201424,1992-10-08,"Strada Dumitrescu Nr. 98 Bl. 52  Sc. 10 Ap. 946, Topoloveni, 426727",0240 470 088,fe:1e:56:15:ea:e6,46.201.17.107,RO80OSHJ0224373664863771,2025-03-11 18:21:07,19056,856,145,1666334
Expected Number of Columns: 16 Found: 15
Possible fixes:
* Enable null padding (null_padding=true) to replace missing values with NULL
* Enable ignore errors (ignore_errors=true) to skip this row

  file=/opt/***/data/raw_data.csv
  delimiter = , (Auto-Detected)
  quote = " (Auto-Detected)
  escape = " (Auto-Detected)
  new_line = \n (Auto-Detected)
  header = true (Set By User)
  skip_rows = 0 (Auto-Detected)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding=0
  sample_size=20480
  ignore_errors=false
  all_varchar=0


[2025-05-05T13:30:40.820+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-05T13:30:40.853+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-05T13:30:40.858+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
