[2025-04-17T07:43:06.254+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T07:43:06.274+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-17T07:35:00+00:00 [queued]>
[2025-04-17T07:43:06.287+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-17T07:35:00+00:00 [queued]>
[2025-04-17T07:43:06.288+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-17T07:43:06.315+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_trusted> on 2025-04-17 07:35:00+00:00
[2025-04-17T07:43:06.323+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=210) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-17T07:43:06.325+0000] {standard_task_runner.py:72} INFO - Started process 215 to run task
[2025-04-17T07:43:06.326+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_trusted', 'scheduled__2025-04-17T07:35:00+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/lead_data_pipeline.py', '--cfg-path', '/tmp/tmpxi4kqjt1']
[2025-04-17T07:43:06.328+0000] {standard_task_runner.py:105} INFO - Job 222: Subtask run_dbt_trusted
[2025-04-17T07:43:06.396+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-17T07:35:00+00:00 [running]> on host c0ac39583bd8
[2025-04-17T07:43:06.596+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_trusted' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T07:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T07:35:00+00:00'
[2025-04-17T07:43:06.598+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T07:43:06.618+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-17T07:43:06.621+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:trusted']
[2025-04-17T07:43:06.636+0000] {subprocess.py:86} INFO - Output:
[2025-04-17T07:43:06.638+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-04-17T07:43:06.640+0000] {subprocess.py:93} INFO - + dbt run --select tag:trusted
[2025-04-17T07:43:09.554+0000] {subprocess.py:93} INFO - [0m07:43:09  Running with dbt=1.8.0
[2025-04-17T07:43:09.993+0000] {subprocess.py:93} INFO - [0m07:43:09  Registered adapter: postgres=1.8.2
[2025-04-17T07:43:10.601+0000] {subprocess.py:93} INFO - [0m07:43:10  Found 9 models, 10 sources, 428 macros
[2025-04-17T07:43:10.605+0000] {subprocess.py:93} INFO - [0m07:43:10
[2025-04-17T07:43:10.753+0000] {subprocess.py:93} INFO - [0m07:43:10  Concurrency: 1 threads (target='dev')
[2025-04-17T07:43:10.754+0000] {subprocess.py:93} INFO - [0m07:43:10
[2025-04-17T07:43:10.768+0000] {subprocess.py:93} INFO - [0m07:43:10  1 of 4 START sql table model lead_trusted.non_pii_data ......................... [RUN]
[2025-04-17T07:47:17.604+0000] {subprocess.py:93} INFO - [0m07:47:17  1 of 4 ERROR creating sql table model lead_trusted.non_pii_data ................ [[31mERROR[0m in 246.83s]
[2025-04-17T07:47:17.609+0000] {subprocess.py:93} INFO - [0m07:47:17  2 of 4 START sql table model lead_trusted.payment_data ......................... [RUN]
[2025-04-17T07:48:00.392+0000] {subprocess.py:93} INFO - [0m07:48:00  2 of 4 OK created sql table model lead_trusted.payment_data .................... [[32mSELECT 9086605[0m in 42.78s]
[2025-04-17T07:48:00.395+0000] {subprocess.py:93} INFO - [0m07:48:00  3 of 4 START sql table model lead_trusted.pii_data ............................. [RUN]
