[2025-04-15T07:22:03.283+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T07:22:03.396+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_staging scheduled__2025-04-15T07:06:00+00:00 [queued]>
[2025-04-15T07:22:03.449+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_staging scheduled__2025-04-15T07:06:00+00:00 [queued]>
[2025-04-15T07:22:03.452+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-15T07:22:03.537+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_staging> on 2025-04-15 07:06:00+00:00
[2025-04-15T07:22:03.563+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3553) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-15T07:22:03.574+0000] {standard_task_runner.py:72} INFO - Started process 3565 to run task
[2025-04-15T07:22:03.578+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_staging', 'scheduled__2025-04-15T07:06:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/lead_data_pipeline.py', '--cfg-path', '/tmp/tmpxnzdlcz2']
[2025-04-15T07:22:03.587+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask run_dbt_staging
[2025-04-15T07:22:03.880+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_staging scheduled__2025-04-15T07:06:00+00:00 [running]> on host c0ac39583bd8
[2025-04-15T07:22:04.504+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T07:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-15T07:06:00+00:00'
[2025-04-15T07:22:04.511+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-15T07:22:04.621+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-15T07:22:04.626+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:staging']
[2025-04-15T07:22:04.674+0000] {subprocess.py:86} INFO - Output:
[2025-04-15T07:22:04.688+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-04-15T07:22:04.691+0000] {subprocess.py:93} INFO - + dbt run --select tag:staging
[2025-04-15T07:37:14.288+0000] {job.py:229} INFO - Heartbeat recovered after 905.55 seconds
[2025-04-15T07:37:16.069+0000] {subprocess.py:93} INFO - [0m07:37:16  Running with dbt=1.8.0
[2025-04-15T07:37:16.536+0000] {subprocess.py:93} INFO - [0m07:37:16  Registered adapter: postgres=1.8.2
[2025-04-15T07:37:17.302+0000] {subprocess.py:93} INFO - [0m07:37:17  Found 9 models, 10 sources, 428 macros
[2025-04-15T07:37:17.307+0000] {subprocess.py:93} INFO - [0m07:37:17
[2025-04-15T07:37:17.471+0000] {subprocess.py:93} INFO - [0m07:37:17  Concurrency: 1 threads (target='dev')
[2025-04-15T07:37:17.472+0000] {subprocess.py:93} INFO - [0m07:37:17
[2025-04-15T07:37:17.487+0000] {subprocess.py:93} INFO - [0m07:37:17  1 of 5 START sql table model lead_staging.dim_address .......................... [RUN]
[2025-04-15T07:53:06.264+0000] {job.py:229} INFO - Heartbeat recovered after 931.57 seconds
[2025-04-15T08:07:24.909+0000] {job.py:229} INFO - Heartbeat recovered after 812.37 seconds
[2025-04-15T08:23:12.038+0000] {local_task_job_runner.py:228} ERROR - Heartbeat time limit exceeded!
[2025-04-15T08:23:12.371+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-15T08:23:12.421+0000] {process_utils.py:132} INFO - Sending 15 to group 3565. PIDs of all processes in the group: [3571, 3573, 3621, 3565]
[2025-04-15T08:23:12.428+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 3565
[2025-04-15T08:23:12.436+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-15T08:23:12.654+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-04-15T08:23:12.728+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-04-15T08:23:12.783+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_raw_data_pipeline, task_id=run_dbt_staging, run_id=scheduled__2025-04-15T07:06:00+00:00, execution_date=20250415T070600, start_date=20250415T072203, end_date=20250415T082312
[2025-04-15T08:23:12.840+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-15T08:23:12.900+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3571, status='terminated', started='07:22:04') (3571) terminated with exit code None
[2025-04-15T08:23:12.902+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3565, status='terminated', exitcode=2, started='07:22:03') (3565) terminated with exit code 2
[2025-04-15T08:23:12.902+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3573, status='terminated', started='07:22:04') (3573) terminated with exit code None
[2025-04-15T08:23:12.903+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3621, status='terminated', started='07:37:16') (3621) terminated with exit code None
