[2025-04-15T15:30:28.069+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T15:30:28.233+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-15T07:36:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-04-15T15:30:28.239+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
