[2025-04-17T07:44:29.428+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T07:44:29.445+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-16T07:59:00+00:00 [queued]>
[2025-04-17T07:44:29.455+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-16T07:59:00+00:00 [queued]>
[2025-04-17T07:44:29.455+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-04-17T07:44:29.468+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_trusted> on 2025-04-16 07:59:00+00:00
[2025-04-17T07:44:29.474+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=313) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-17T07:44:29.475+0000] {standard_task_runner.py:72} INFO - Started process 315 to run task
[2025-04-17T07:44:29.476+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_trusted', 'scheduled__2025-04-16T07:59:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/lead_data_pipeline.py', '--cfg-path', '/tmp/tmpi83it3g1']
[2025-04-17T07:44:29.477+0000] {standard_task_runner.py:105} INFO - Job 231: Subtask run_dbt_trusted
[2025-04-17T07:44:29.526+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-16T07:59:00+00:00 [running]> on host c0ac39583bd8
[2025-04-17T07:44:29.614+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_trusted' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T07:59:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-16T07:59:00+00:00'
[2025-04-17T07:44:29.616+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T07:44:29.631+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-17T07:44:29.634+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:trusted']
[2025-04-17T07:44:29.645+0000] {subprocess.py:86} INFO - Output:
[2025-04-17T07:44:29.648+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-04-17T07:44:29.649+0000] {subprocess.py:93} INFO - + dbt run --select tag:trusted
[2025-04-17T07:44:32.165+0000] {subprocess.py:93} INFO - [0m07:44:32  Running with dbt=1.8.0
[2025-04-17T07:44:32.477+0000] {subprocess.py:93} INFO - [0m07:44:32  Registered adapter: postgres=1.8.2
[2025-04-17T07:44:32.945+0000] {subprocess.py:93} INFO - [0m07:44:32  Found 9 models, 10 sources, 428 macros
[2025-04-17T07:44:32.948+0000] {subprocess.py:93} INFO - [0m07:44:32
[2025-04-17T07:44:33.077+0000] {subprocess.py:93} INFO - [0m07:44:33  Concurrency: 1 threads (target='dev')
[2025-04-17T07:44:33.077+0000] {subprocess.py:93} INFO - [0m07:44:33
[2025-04-17T07:44:33.090+0000] {subprocess.py:93} INFO - [0m07:44:33  1 of 4 START sql table model lead_trusted.non_pii_data ......................... [RUN]
[2025-04-17T07:50:22.708+0000] {subprocess.py:93} INFO - [0m07:50:22  1 of 4 ERROR creating sql table model lead_trusted.non_pii_data ................ [[31mERROR[0m in 349.61s]
[2025-04-17T07:50:22.750+0000] {subprocess.py:93} INFO - [0m07:50:22  2 of 4 START sql table model lead_trusted.payment_data ......................... [RUN]
[2025-04-17T07:50:51.406+0000] {subprocess.py:93} INFO - [0m07:50:51  2 of 4 OK created sql table model lead_trusted.payment_data .................... [[32mSELECT 9086605[0m in 28.69s]
[2025-04-17T07:50:51.410+0000] {subprocess.py:93} INFO - [0m07:50:51  3 of 4 START sql table model lead_trusted.pii_data ............................. [RUN]
